### ISSUE TITLE
Not working in Firefox

### ISSUE THREAD

**Issue by sevenmiletechnology** [HaithemMosbahi/full-calendar#14]
The calendar is not rendered in Firefox. I noticed that the demo at https://www.webcomponents.org/element/HaithemMosbahi/scheduler-component/demo/demo/index.html does not render either.

**Comment by HaithemMosbahi** [comment]
Hello,
Thank you for raising this issue. I'm going to check this out and provide a fix as soon as possible.

**Comment by Westbrook** [comment]
This seems like it's related to the console error you get in Chrome `Uncaught TypeError: Cannot read property 'addEventListener' of null at setTimeout (scheduler-component.html:275)` Would it be simpler just to attach the `category-click` to the `categories-element` declaratively? You're waiting "for dom change to complete" but it'll not complete in contexts where `_showCategoriesContainer == false`.

**Comment by sevenmiletechnology** [comment]
I just did a 'bower update' on my project and it now works. I felt like it was some bugs in some of the iron-* components which have been fixed.
