### ISSUE TITLE
Boolean properties should not default to true (e.g. allDaySlot)

### ISSUE THREAD

**Issue by matgnt** [HaithemMosbahi/full-calendar#15]
Hi Mosbahi,

thanks for publishing this component! I just found this minor issue with "true" default values of Boolean properties. I figured out with "allDaySlot" which I couldn't disable through setting the component attribute. I think there are 2 options to fix this:

1) Set the default values of Boolean properties to "false"
(Issue with this fix: It would change the behavior after an update of this component) 
2) Or set the type of those properties to "Object"

The Polymer documentation says: "Boolean. Results in a non-valued attribute to be either set (true) or removed (false)."
Which is not very precise I think. I found a better (but older) explanation here:
https://github.com/Polymer/polymer/issues/1812#issuecomment-112226630

Shall I create a pull request?

Matthias

**Comment by HaithemMosbahi** [comment]
Hello, 

Thank you for raising this issue. Yes, we have a problem here with "true" default values. When I started wrapping the fullCalendar I wanted to stay on the same page with the default values of the library.

I will probably go with the first option which is the custom elements spec / polymer way of dealing with boolean values and thus it's up to the developer to add / remove boolean attributes.

Fortunately, changing the default values of the existing boolean properties to false will not change the behavior of the component.


Yes, you can create a pull request. Your contribution is welcome 😃

**Comment by matgnt** [comment]
Great! I'll make the changes.
What I meant with the behavior of the component was the following example:

A developer uses the component without the "all-day-slot" attribute and up until now, he can see the day slot in the calendar, because the default is true. When I change it to false now, it's not visible anymore until he adds this attribute to his code. Which means a code change is necessary with this update to keep the same look and feel as before. I'm not sure how many developers would be affected by that.

What do you think?

**Comment by HaithemMosbahi** [comment]
Yes I agree with you. However, I think both options may require some changes in the developer's code. Even with the Object type, the developer has to change all boolean attributes to meet the object syntax ( all-day-slot="true" ).

We will release a new version and we will mention all these changes in the documentation. 

_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by HaithemMosbahi** [comment]
This issue has been fixed on version 1.4.0
