### ISSUE TITLE
RFC: "date-range-changed" event

### ISSUE THREAD

**Issue by matgnt** [HaithemMosbahi/full-calendar#17]
I want to load calendar event items from outside the scheduler-component, based on the date (or date range) that is selected inside the scheduler-component (with the navigation bar). To do so, I listen to "on-view-render" events and check for "detail.view.activeRange.start" and "end".

Implementing this, I thought this should be part of the "scheduler-component" itself. After a view-render event only if the "start" or "end" has changed, fire the new "date-range-changed" event with 2 arguments, a "from" and "to" date (as text or a moment.js object).

Does this make sense? Should I build this into the scheduler-component?
Please let me know your comments.

**Comment by HaithemMosbahi** [comment]
Hello, 
Yes, I think this totally makes sense ! Adding this feature to scheduler-component would be very useful, especially when there's a need for a lazy loading based on the date.
Actually, this feature is supported in the fullCelndar library 
Take a look at this link : https://fullcalendar.io/docs/event_data/events_function/
There are several manners to fetch events into the calendar : 
* Events as an array ( This is the one used in the scheduler-component, because it allow )
* Events as a callback function : the interesting part about this approach is that the function is triggered when the user clicks prev/next or switches views ( This is what we need to achieve ) 
* Events as json feed.

So I think we can build something inspired from the events callback function.

**Comment by matgnt** [comment]
The callback function approach sounds interesting. How would we trigger event changes from outside the component? e.g. new events are added by other users. Would we just call a refetch function manually, which then triggers the same callback with the date range?

The other option was to stick with setting the event array and leave the loading completely outside. Just inform the outside world of what has changed in the view.

**Comment by HaithemMosbahi** [comment]
I think that it would be better to stick with the event array option and to emit every change 
that may require a refetch ( an update of the event's array property ). 

So I believe that your suggestion of emitting the date-range-changed event is the best solution
so far. Thus, communication with the outside world will remain based on properties / events. 
Then, it's up to developers to listen to events and to update the scheduler inputs when 
it's needed.

**Comment by HaithemMosbahi** [comment]
Would you like to add this feature as a pull request ?

**Comment by matgnt** [comment]
Sounds good! I'll implement this.

**Comment by matgnt** [comment]
Actually I found out, that the view-render event is fired only in those cases that we need.
The fullcalendar documentation says:

"This callback will get triggered when the user changes the view, or when any of the date navigation methods are called."

Only the naming and maybe the parameters could be improved, I think.

Seems our options are:

1. **Replace** "view-render(...)" with "date-range-changed(detail: view.activeRange)"
2. Fire "date-range-changed" **in addition** to the "view-render" event.
3. Leave code as is and update documentation to make clear that "view-render" event is fired only when the visible date range has changed.

I would go for 2. That's easy to understand for new developers and for those with fullcalendar API knowledge. And it's backward compatible.

What do you think?

**Comment by HaithemMosbahi** [comment]
Hello, 
sorry for my late answer. 
Yes I agree with, I think the second option is the best solution. As you have mentioned, it wouldn't break existing code, we will only fire a new event that will make detecting date range change more easy.

**Comment by HaithemMosbahi** [comment]
Fixed by #23
