### ISSUE TITLE
Enable select centric config properties.

### ISSUE THREAD

**Issue by Westbrook** [HaithemMosbahi/full-calendar#18]
Nice work on this @HaithemMosbahi! Super useful for me and my team.

I'm looking at wanting to do somethings around selecting new events (especially in the `agendaWeek` view), and wondered if it made sense to you to add something on the order of:

```
selectable: this.selectable,
selectHelper: this.selectHelper,
select: (start, end, jsEvent, view) => {
  this.dispatchEvent(new CustomEvent('select', { detail: { start, end, jsEvent, view } }));
},
```

To act as appropriate push throughs to `.fullCalendar(this._config)`?

It's close to what I'm working with locally and I'd be happy to supply a PR for it.

**Comment by HaithemMosbahi** [comment]
Hello @Westbrook 
I am glad you found my work useful and helpful.
Yes, the idea is to support the features offered by the fullCalendar library as much as possible. So, this totally makes sense to me.
As you have mentioned, these new properties should be added to this._config object.
You can create a PR and I'd be happy to merge it.

**Comment by Westbrook** [comment]
Fixed by https://github.com/HaithemMosbahi/scheduler-component/pull/19
